---
title: "Draft Quarto document"
author: "Your Name"
format: html
execute: 
    echo: true
editor: 
    markdown:
        wrap: 72
        canonical: true 
---

## 

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
targets::tar_config_set(store = here::here("_targets"))

library(tidyverse)
library(targets)
library(tidymodels)

source(here::here("R", "functions.R"))

lipidomics <- tar_read(lipidomics)

```

## Basic statistics

```{r basic-stats}
# getting the mean and sd of each metabolite

targets::tar_read(basic_stats_metabolites_mean_sd) %>% 
    mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>% 
    select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
    knitr::kable(caption = "Descriptive statistics of the metabolites.")

```

## Creating figure of metabolite levels

```{r metabolite-figure}
#  making plot of distributions of metabolites

targets::tar_read(fig_metabolite_distributions)

```

## Models

```{r building-model}

log_reg_specs <- logistic_reg() %>% 
    set_engine("glm")
log_reg_specs

lipidomics %>% 
    count(code, metabolite) %>% 
    filter(n > 1)

lipidomics_wide <- lipidomics %>%
  mutate(metabolite = snakecase::to_snake_case(metabolite)) %>%
  pivot_wider(
    names_from = metabolite,
    values_from = value,
    values_fn = mean,
    names_prefix = "metabolite_"
  )
lipidomics_wide

lipidomics %>%
  column_values_to_snake_case() %>% 
    glimpse()

lipidomics %>%
    metabolites_to_wider() %>% 
    str()


create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"), #model specs
  lipidomics_wide %>%
    create_recipe_spec(metabolite_cholesterol) #recipes specs
) %>%
  fit(lipidomics_wide) %>% #why using fit and data here?
  tidy_model_output()
```
